name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label: I have updated to the latest version of the plugin.
          required: true
        - label: I have read the README, including the section "Special cases."
          required: true
        - label: I have searched the existing issues for this plugin.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction & Sample Text
      description: >
        Include sample text and mark clearly where the cursor is before the operation, the exact
        operation you used, where it is afterwards, and where you expected it be.
      placeholder: |
        operation used: `e`
        before  : Sample Text
        ------------^---------
        after   : Sample Text 
        ---------------^-----
        expected: Sample Text
        -----------------^---
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: neovim version
      render: Text
    validations:
      required: true
  - type: textarea
    id: special-settings
    attributes:
      label: Special Settings
      description:
        Do you have any special settings enabled that alter vim's editing behavior, such as
        `virtualedit=onemore`?
      render: Text
