name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction & Sample Text
      description: Include sample text and mark clearly where the cursor is before the operation, where it is afterwards, and where you expected it be.
      placeholder: |
        before: Samp|le Text
        after: Sample |Text 
        expected: Sample| Text
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: neovim version
      render: Text
    validations:
      required: true
  - type: textarea
    id: special-settings
    attributes:
      label: Special Settings
      description: Do you have any special settings enabled that alter vim's editing behavior, like `virtualedit=onemore`?
      render: Text
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label: In case I have an issue with using the motions in operater-pending mode (`cw`, `de`, …), I read the [notes on operator-pending mode in the README](https://github.com/chrisgrieser/nvim-spider#notes-on-operator-pending-mode).
          required: true
        - label: I have updated to the latest version of the plugin.
          required: true
